FreskiProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('catalog/', include('catalog.urls'))
]

catalog/urls.py
from django.urls import path
from catalog import views

app_name = 'catalog_app'

urlpatterns = [
    path('', views.fresco, name='catalog'),
    path('fresco', views.fresco, name='fresco'),
    path('fretwork', views.fretwork, name='fretwork'),
    path('glue', views.glue, name='glue'),
]

common/urls.py
from django.conf.urls.static import static
from django.urls import path

from FreskiProject import settings
from common import views

app_name = 'common_app'

urlpatterns = [
                  path('', views.index, name='index'),
                  path('about', views.about, name='about'),
                  path('contacts', views.contacts, name='contacts'),
                  path('examples', views.examples, name='examples'),
                  path('examples/get/<int:id_to_get>', views.examples_get, name='examples_get'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


class Provider(models.Model):
    name = models.CharField(max_length=250, verbose_name='Описание', blank=False, null=False)
    provider_link = models.CharField(max_length=250, blank=True, null=True, verbose_name='Ссылка на поставщика')

    def __str__(self):
        return self.name


class FrescoProvider(Provider):
    provider_img = models.ImageField(upload_to='catalog/fresco', blank=True, null=True, verbose_name='Логотип')

    class Meta:
        verbose_name = 'Фрески'
        verbose_name_plural = 'Фрески'


class FretworkProvider(Provider):
    provider_img = models.ImageField(upload_to='catalog/fretwork', blank=True, null=True, verbose_name='Логотип')

    class Meta:
        verbose_name = 'Лепнина'
        verbose_name_plural = 'Лепнина'


class GlueProvider(Provider):
    provider_img = models.ImageField(upload_to='catalog/glue', blank=True, null=True, verbose_name='Фото товара')
    price = models.CharField(max_length=150, verbose_name='Цена', null=False, blank=False)

    provider_country = models.CharField(max_length=250, verbose_name='Страна производитель', null=True, blank=True)
    rate = models.CharField(max_length=250, verbose_name='Расход', null=True, blank=True)

    class Meta:
        verbose_name = 'Клей'
        verbose_name_plural = 'Клей'

common/models.py
from django.db import models


# Examples with Images
class Example(models.Model):
    name = models.CharField(max_length=250, verbose_name='Описание')
    producer = models.CharField(max_length=250, blank=True, null=True, verbose_name='Производитель')
    default_image = models.ImageField(upload_to='examples/', blank=True, null=True, verbose_name='Основная картика')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Пример работы'
        verbose_name_plural = 'Примеры работ'


class ExampleImage(models.Model):
    example = models.ForeignKey(Example, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='examples/', verbose_name='Картинка')

    def __str__(self):
        return self.example.name

    class Meta:
        verbose_name = 'Пример (картинка)'
        verbose_name_plural = 'Галерея проекта'


# Contacts
class Contact(models.Model):

    CONTACT_CHOICES = (
        ('Адрес', 'Адрес'),
        ('Телефон', 'Телефон'),
        ('Email', 'Email'),
        ('Расписание', 'Расписание')
    )

    tag = models.CharField(max_length=15, unique=True, verbose_name='Тип',
                           choices=CONTACT_CHOICES, default='Адрес')
    value = models.CharField(max_length=250, unique=True, verbose_name='Значение')

    def __str__(self):
        return self.tag

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

catalog/views.py
from django.shortcuts import render
from .models import FrescoProvider, FretworkProvider, GlueProvider


# Create your views here.
def fresco(request):
    fresco_list = FrescoProvider.objects.all()
    return render(request, 'catalog/fresko.html', {'fresco_list': fresco_list})


def fretwork(request):
    fretwork_list = FretworkProvider.objects.all()
    return render(request, 'catalog/fretwork.html', {'fretwork_list': fretwork_list})


def glue(request):
    glue_list = GlueProvider.objects.all()
    return render(request, 'catalog/glue.html', {'glue_list': glue_list})

common/views.py
from django.shortcuts import render
from django.http import HttpResponse
import json
from django.core.serializers import serialize
from .models import Example, ExampleImage, Contact


# Create your views here.
def index(request):
    exampls = list(Example.objects.all()[:4])
    return render(request, 'common/index.html', {'examples': exampls})


def about(request):
    return render(request, 'common/about.html')


def contacts(request):
    return render(request, 'common/contacts.html')


def examples(request):
    exampls = list(Example.objects.all())
    return render(request, 'common/examples.html', {'examples': exampls})


def examples_get(request, id_to_get: int):
    example = Example.objects.get(pk=id_to_get)
    objects_img = list(ExampleImage.objects.filter(example=example))

    img_dict = dict()
    img_dict[str(example.default_image)] = str(example.default_image)
    for img in objects_img:
        img_dict[str(img.image)] = str(img.image)

    return HttpResponse(json.dumps(img_dict), content_type='application/json')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block page_title %}
        {% endblock %}
    </title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Bad+Script&family=Caveat&family=Roboto:wght@500&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <script defer src="{% static 'js/all.js' %}"></script>
</head>
<body class="d-flex flex-column h-100 montserrat-font">
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top" id="mainNav">
    <div class="container-fluid">
        <a class="navbar-brand m-0" href="{% url 'common_app:index' %}">
            <img src="/media/logo.png" alt="" class="d-inline-block align-text-top">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="container-fluid collapse navbar-collapse nav-links" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link main-nav-link" aria-current="page"
                       href="{% url 'common_app:index' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link main-nav-link" href="{% url 'catalog_app:fresco' %}">Каталог</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link main-nav-link" href="{% url 'common_app:examples' %}">Примеры работ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link main-nav-link" href="{% url 'common_app:about' %}">О нас</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link main-nav-link" href="{% url 'common_app:contacts' %}">Контакты</a>
                </li>
            </ul>
            <p class="text-black contacts nav-contact">
                <i class="fas fa-phone-alt mr-3"></i>
                {{ contacts.Телефон }}
            </p>
        </div>
    </div>
</nav>


<!-- Main Block -->
{% block main_block %}

{% endblock %}

<!-- Footer -->
<footer class="footer footer-bg">
    <!-- Section: Links  -->
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase text-white fw-bold cursor-default">Ссылки</h6>
                    <hr
                            class="mb-4 mt-0 d-inline-block mx-auto"
                            style="width: 60px; background-color: #fcfbf9; height: 2px;opacity: 100;"
                    />
                    <p>
                        <a href="{% url 'common_app:index' %}" class="footer-link fw-bold">Главная</a>
                    </p>
                    <p>
                        <a href="{% url 'catalog_app:fresco' %}" class="footer-link fw-bold">Каталог</a>
                    </p>
                    <p>
                        <a href="{% url 'common_app:examples' %}" class="footer-link fw-bold">Примеры работ</a>
                    </p>
                    <p>
                        <a href="{% url 'common_app:about' %}" class="footer-link fw-bold">О нас</a>
                    </p>
                    <p>
                        <a href="{% url 'common_app:contacts' %}" class="footer-link fw-bold">Контакты</a>
                    </p>
                </div>

                <!-- Catalog -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase text-white fw-bold cursor-default">Каталог</h6>
                    <hr
                            class="mb-4 mt-0 d-inline-block mx-auto"
                            style="width: 60px; background-color: #fcfbf9; height: 2px;opacity: 100;"
                    />
                    <p>
                        <a href="{% url 'catalog_app:fresco' %}" class="footer-link fw-bold">Фрески</a>
                    </p>
                    <p>
                        <a href="{% url 'catalog_app:fretwork' %}" class="footer-link fw-bold">Лепнина</a>
                    </p>
                    <p>
                        <a href="{% url 'catalog_app:glue' %}" class="footer-link fw-bold">Клей</a>
                    </p>
                </div>

                <!-- Contacts -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase text-white fw-bold cursor-default">Контакты</h6>
                    <hr
                            class="mb-4 mt-0 d-inline-block mx-auto"
                            style="width: 60px; background-color: #fcfbf9; height: 2px;opacity: 100;"
                    />
                    <p class="text-white contacts fw-bold mb-0">
                        <i class="fas fa-map-marker-alt mr-3"></i>
                        {{ contacts.Адрес }}
                    </p>
                    <p class="text-white contacts" style="font-size: 0.8rem; margin-left: 1rem">{{ contacts.Расписание.0}} {{ contacts.Расписание.1}}
                        <br>
                        {{ contacts.Расписание.2}}й</p>
                    <p class="text-white contacts fw-bold">
                        <i class="fas fa-envelope mr-3"></i>
                        {{ contacts.Email }}
                    </p>
                    <p class="text-white contacts fw-bold">
                        <i class="fas fa-phone-alt mr-3"></i>
                        {{ contacts.Телефон }}
                    </p>
                    <p class="text-white" style="font-size: 2rem">
                        <a href="#" class="social-link">
                            <i class="fab fa-facebook-square"></i>
                        </a>
                        <a href="#" class="social-link">
                            <i class="fab fa-instagram-square"></i>
                        </a>
                        <a href="#" class="social-link">
                            <i class="fab fa-telegram"></i>
                        </a>
                        <a href="#" class="social-link">
                            <i class="fab fa-whatsapp-square"></i>
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </section>

    <!-- Copyright -->
    <div class="text-center p-3"
         style="background-color: rgba(0, 0, 0, 0.2)">
        © 2021 Все права защищены
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/catalog/catalog.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block page_title %}
    Каталог
{% endblock %}

{% block main_block %}

    <div class="container-fluid page-header">
        <div class="w-100 page-header-underline d-flex">
            <h4>Каталог</h4>
            <h4>&nbsp;>&nbsp;</h4>
            {% block current_cat_name %}

            {% endblock %}
        </div>
        <div class="w-100 container-fluid d-flex flex-row catalog">
            <div class="catalog-categories" style="width: 15rem">
                <a class="btn btn-beige category" href="{% url 'catalog_app:fresco' %}">Фрески</a>
                <a class="btn btn-brown category" href="{% url 'catalog_app:fretwork' %}">Лепнина</a>
                <a class="btn btn-gray category" href="{% url 'catalog_app:glue' %}">Клей</a>
            </div>
            <div class="container-fluid" style="padding-right: 0; padding-left: 2rem">
                <div>
                    {# Product description #}
                    {% block product_desc %}

                    {% endblock %}
                </div>
                <div class="row row-cols-1 row-cols-sm-1 row-cols-xl-2 row-cols-xxl-3  row-cols-xxxl-4 g-3">
                    {# Products/catalogs cards #}
                    {% block product_cards %}

                    {% endblock %}
                </div>
            </div>
        </div>

    </div>


{% endblock %}

templates/catalog/fresko.html
<!DOCTYPE html>
{% extends 'catalog/catalog.html' %}


{% block current_cat_name %}
    <h4>Фрески</h4>
{% endblock %}


{% block product_desc %}
    <div class="product-desc">
        <p>Мы работаем с поставщиваки напрямуцю, поэтому смотрите каталоги у них</p>
    </div>
{% endblock %}


{% block product_cards %}
    {% for fresco in fresco_list %}
        <div class="col">
            <div class="card mb-3 catalog-product"
                 onclick="openUrl('{{ fresco.provider_link }}');">
                <div class="d-flex justify-content-center goods-img-top">
                    <img src="/media/{{ fresco.provider_img }}" class="card-img-top" alt="...">
                </div>
                <div class="card-body goods-desc">
                    <p class="card-text text-center fs-6 product-name" style="text-decoration: underline #a78d6e">
                        {{ fresco.name }}
                    </p>
                    <div class="bg-gray-dark goods-action d-flex justify-content-center">
                        <p class="goods-action-label">Перейти</p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/catalog/fretwork.html
<!DOCTYPE html>
{% extends 'catalog/catalog.html' %}


{% block current_cat_name %}
    <h4>Лепнина</h4>
{% endblock %}


{% block product_desc %}
    <div class="product-desc">
        <p>Лепнины описание это</p>
    </div>
{% endblock %}


{% block product_cards %}
    {% for fretwork in fretwork_list %}
        <div class="col">
            <div class="card mb-3 catalog-product"
                 onclick="openUrl('{{ fretwork.provider_link }}');">
                <div class="d-flex justify-content-center goods-img-top">
                    <img src="/media/{{ fretwork.provider_img }}" class="card-img-top" alt="...">
                </div>
                <div class="card-body goods-desc">
                    <p class="card-text text-center fs-6 product-name" style="text-decoration: underline #a78d6e">
                        {{ fretwork.name }}
                    </p>
                    <div class="bg-gray-dark goods-action d-flex justify-content-center">
                        <p class="goods-action-label">Перейти</p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/catalog/glue.html
<!DOCTYPE html>
{% extends 'catalog/catalog.html' %}


{% block current_cat_name %}
    <h4>Клей</h4>
{% endblock %}


{% block product_desc %}
    <div class="product-desc">
        <p>Описание клея</p>
    </div>
{% endblock %}


{% block product_cards %}
    {% for glue in glue_list %}
        <div class="col">
            <a class="card catalog-product glue">
                <div class="d-flex justify-content-center goods-img-top">
                    <img src="/media/{{ glue.provider_img }}" class="card-img-top" alt="...">
                </div>
                <div class="card-body goods-desc">
                    <p class="card-text text-center fs-6 product-card-desc">
                        {{ glue.name }}
                    </p>

                    <div class="characteristic">
                        {% if glue.provider_country is not Null %}
                            <div class="d-flex justify-content-between char-line">
                                <p class="char">Страна</p>
                                <div class="connection-line"></div>
                                <p class="char">{{ glue.provider_country }}</p>
                            </div>
                        {% endif %}
                        {% if glue.rate is not Null %}
                            <div class="d-flex justify-content-between char-line">
                                <p class="char">Расход</p>
                                <div class="connection-line"></div>
                                <p class="char">{{ glue.rate }}</p>
                            </div>
                        {% endif %}
                    </div>

                    {% if glue.price is not Null %}
                        <div class="bg-gray-dark goods-action d-flex justify-content-center">
                            <p class="goods-action-label">{{ glue.price }}</p>
                        </div>
                    {% endif %}
                </div>
            </a>
        </div>
    {% endfor %}
{% endblock %}

templates/common/about.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block page_title %}О нас{% endblock %}


{% block main_block %}
    <div class="container-fluid page-header">
        <div class="w-100 page-header-underline">
            <h4>О нас</h4>
        </div>
        <div class="row row-cols-1 row-cols-xxl-1 row-cols-xxxl-2 mt-3 about-row">
            <div class="col img-left-col">
                <div class="section-img-1">
                    <img src="/media/freski-ecodecor.jpg" alt="...">
                </div>
            </div>
            <div class="col" style="padding: 1rem">
                <div class="d-flex about-text-box">
                    <p class="about-text" style="text-align: start">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque similique velit
                        voluptatibus! Animi asperiores at, autem blanditiis cum harum inventore iste libero maxime
                        mollitia quod reiciendis soluta suscipit vitae voluptate! Accusantium asperiores, aut commodi
                        distinctio error inventore itaque iure maiores mollitia perferendis reiciendis saepe. Ab autem
                        consectetur corporis delectus earum eveniet, ex harum illum iure laborum neque nesciunt quas
                        quidem soluta sunt? Aut doloribus exercitationem iure nulla officia perferendis saepe.
                    </p>
                </div>
            </div>
        </div>
        <div class="row row-cols-1 row-cols-xxl-1 row-cols-xxxl-2 mt-3">
            <div class="col" style="padding: 1rem">
                <div class="d-flex about-text-box">
                    <p class="about-text" style="text-align: end">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque similique velit
                        voluptatibus! Animi asperiores at, autem blanditiis cum harum inventore iste libero maxime
                        mollitia quod reiciendis soluta suscipit vitae voluptate! Accusantium asperiores, aut commodi
                        distinctio error inventore itaque iure maiores mollitia perferendis reiciendis saepe. Ab autem
                        consectetur corporis delectus earum eveniet, ex harum illum iure laborum neque nesciunt quas
                        quidem soluta sunt? Aut doloribus exercitationem iure nulla officia perferendis saepe.
                    </p>
                </div>
            </div>
            <div class="col img-right-col">
                <div class="section-img-2">
                    <img src="/media/freski-ecodecor.by2.jpg" alt="...">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/common/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block page_title %}
    Главная
{% endblock %}


{% block main_block %}
    <!-- Carousel -->
    <div id="myCarousel" class="carousel slide">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true"
                    aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="/media/freski-ecodecor.by2.jpg" alt="" class="carousel-img">

                <div class="container">
                    <div class="carousel-caption text-start">
                        <h1>Фрески</h1>
                        <p>Заказывайте фрески (надо придумать тексты)</p>
                        <p><a class="btn btn-brown" href="{% url 'catalog_app:fresco' %}">Каталог фресок</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img src="/media/freski-ecodecor.by2.jpg" alt="" class="carousel-img">

                <div class="container">
                    <div class="carousel-caption">
                        <h1>Лепнина</h1>
                        <p>Заказывайте лепнину (придумать текст)</p>
                        <p><a class="btn btn-brown" href="{% url 'catalog_app:fretwork' %}">Каталог лепнины</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img src="/media/freski-ecodecor.by2.jpg" alt="" class="carousel-img">

                <div class="container">
                    <div class="carousel-caption text-end" >
                        <h1>Клей</h1>
                        <p>Не нюхайте клей</p>
                        <p><a class="btn btn-brown" href="{% url 'catalog_app:glue' %}">Каталог клея</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Sells -->
    <div class="container-fluid marketing page-section">
        <div class="text-center">
            <h2 class="section-heading bad-script-font">Наши каталоги</h2>
        </div>
        <!-- Three columns of text below the carousel -->
        <div class="row d-flex justify-content-evenly">
            <div class="col-lg-3">
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140"
                     xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#777"/>
                    <text x="50%" y="50%" fill="#777" dy=".3em">140x140</text>
                </svg>

                <h4 class="my-4 bad-script-font f-3-rem">Фрески</h4>
                <p class="text-muted text-sells">Some representative placeholder content for the three columns of text
                    below the
                    carousel. This is the
                    first column.</p>
                <p><a class="btn btn-gray" href="{% url 'catalog_app:fresco' %}">ПОСМОТРЕТЬ В КАТАЛОГЕ</a></p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-3">
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140"
                     xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#777"/>
                    <text x="50%" y="50%" fill="#777" dy=".3em">140x140</text>
                </svg>

                <h4 class="my-4 bad-script-font f-3-rem">Лепнина</h4>
                <p class="text-muted text-sells">Another exciting bit of representative placeholder content. This time,
                    we've moved
                    on to the second
                    column.</p>
                <p><a class="btn btn-gray" href="{% url 'catalog_app:fretwork' %}">ПОСМОТРЕТЬ В КАТАЛОГЕ</a></p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-3">
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140"
                     xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#777"/>
                    <text x="50%" y="50%" fill="#777" dy=".3em">140x140</text>
                </svg>

                <h4 class="my-4 bad-script-font f-3-rem">Клей</h4>
                <p class="text-muted text-sells">And lastly this, the third column of representative placeholder
                    content.</p>
                <p><a class="btn btn-gray" href="{% url 'catalog_app:glue' %}">ПОСМОТРЕТЬ В КАТАЛОГЕ</a></p>
            </div>
        </div>
    </div>

    <!-- Freski 1 row -->
    <div class="container-fluid">
        <div class="row" style="background: #f6f5f1">
            <div class="col-lg-6 showcase-img" style="background-image: url('/media/freski-ecodecor.by2.jpg')"></div>
            <div class="col-lg-6 my-auto showcase-text" style="padding-left: 12rem; padding-right: 12rem;">
                <h2 style="font-size: 2rem">Fully Responsive Design</h2>
                <p class="lead mb-0" style="margin-top: 2rem; font-size: 1.5rem;">When you use a theme created by Start
                    Bootstrap, you know that the theme will look
                    great on any device, whether it's a phone, tablet, or desktop the page will behave responsively!</p>
            </div>
        </div>
    </div>

    <!-- Work examples -->
    <div class="container-fluid my-auto" style="min-height: 50rem;">
        <div class="container d-flex justify-content-center" style="margin-top: 4rem">
            <h1 class="align-self-center bad-script-font f-3-rem">Примеры работ</h1>
        </div>
        <div class="row d-flex justify-content-center" style="margin-top: 4rem">
            {% for example in examples %}
                <div class="card align-self-center mx-4 mb-3 work-example work-example-{{ forloop.counter }}"
                onclick="openUrlSameTab('/examples')">
                    <div class="card-body">
                        <p class="card-text text-center fs-6 mt-3 example-num">Пример #{{ forloop.counter }}</p>
                        <div class="d-flex" style="min-height: 10rem">
                            <p class="card-text align-self-center text-uppercase text-center fs-4">{{ example.name }}</p>
                        </div>
                    </div>
                    <div>
                        <img src="/media/{{ example.default_image }}" class="card-img-bottom" alt="...">
                    </div>
                    <div class="w-100 d-flex justify-content-center producer" style="min-height: 2rem; padding-top: 0.2rem;">
                        {% if examples.0.producer is not None %}
                            <a class="text-white" href="#" style="text-decoration: none">{{ example.producer }}</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- Lepnina 2 row -->
    <div class="container-fluid">
        <div class="row" style="background: #f6f5f1">
            <div class="col-lg-6 my-auto showcase-text" style="padding-left: 12rem; padding-right: 12rem;">
                <h2 style="font-size: 2rem">Fully Responsive Design</h2>
                <p class="lead mb-0" style="margin-top: 2rem; font-size: 1.5rem;">When you use a theme created by Start
                    Bootstrap, you know that the theme will look
                    great on any device, whether it's a phone, tablet, or desktop the page will behave responsively!</p>
            </div>
            <div class="col-lg-6 showcase-img" style="background-image: url('/media/freski-ecodecor.by2.jpg')"></div>
        </div>
    </div>

{% endblock %}